config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  root 'jobs#index'

end

app/models/job.rb
# Class Job
class Job < ActiveRecord::Base
  validates :title, presence: true
  validates :description, presence: true
  validates :company, presence: true
  validates :url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
# Class JobsController
class JobsController < ApplicationController
  def index
    @jobs = Job.page(params[:page]).per(6)
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(params.require(:job).permit(:title, :description, :company, :url))
    if @job.save
      redirect_to root_path
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/index.html.erb
<div class="container-full">
  <div class="row">
    <div class="col-lg-12 text-center v-center">
      <h1>Jobs</h1>
      <p class="lead">A simple Jobs Board!</p>
    </div>
  </div>
</div>

<div class="container">
  <hr>
  <% @jobs.each do |job| %>
    <div class="job">
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading"><h3><%= link_to job.title, job.url %></h3></div>
          <div class="panel-body">
            <%= job.description %><br/>
            <strong><%= job.company %></strong>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="container">
  <p><%= link_to "Add a job", new_job_path %></p>
</div>
<p><%= paginate @jobs %></p>

app/views/jobs/new.html.erb
<div class="form-group">
  <%= simple_form_for @job do |form| %>
    <%= form.input :title, label: "Job title" %>
    <%= form.input :description, label: "Description" %>
    <%= form.input :company, label: "Your company" %>
    <%= form.input :url, label: "Link to job" %>
    <%= form.button :submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jobsboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>